name: Update Profile README

on:
  schedule:
     - cron: "* * * * *"  # Runs every min
  workflow_dispatch:     # Allows manual run from GitHub UI

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install PyGithub

      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python update_readme.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update README with repo activity"
          git push
